export default function DisclaimerPage() {
  return (
    <div 
      style={{ fontFamily: "'Times New Roman', Times, serif" }} 
      className="max-w-4xl mx-auto p-12 text-gray-900 leading-relaxed text-justify"
    >
      {/* Titlu Oficial */}
      <h1 className="text-3xl font-bold mb-8 text-center text-red-600 uppercase border-b-2 border-red-600 pb-2">
        Academic Disclaimer & Clinical Notice
      </h1>

      <div className="space-y-6 text-lg">
        {/* AVERTISMENTUL CLINIC (Evidențiat) */}
        <div className="bg-red-50 border-2 border-red-600 p-6 my-8">
          <p className="font-bold text-xl mb-2 text-red-700">Attention / Clinical Notice:</p>
          <p className="italic">
           Please, keep in mind that the profiles results does not possess CLINICAL RELEVANCE. 
        
The personality profiles and results generated by this platform are based solely on self-reported questionnaire data collected for academic research purposes. They do not constitute clinical assessments, psychological diagnoses, or medical evaluations of any kind. The results should not be interpreted as a substitute for professional psychological or psychiatric advice. Any formal clinical evaluation can only be conducted by a licensed mental health professional or specialist. If you have concerns about your mental health or psychological well-being, please consult a qualified healthcare provider. 
            
          </p>
        </div>

        {/* DETALII ACADEMICE (Textul tău anterior) */}
        <section className="space-y-4">
          <p>
            This platform was developed exclusively for academic research purposes as part of a doctoral study. 
            Its creators receive no remuneration and derive no material benefit from its use or access.
          </p>
          
          <p>
            The tools provided here are intended for data collection within a scientific framework and 
            should not be used as a substitute for professional mental health advice, diagnosis, or treatment.
          </p>
        </section>

        {/* GDPR & COPYRIGHT (Varianta scurtă) */}
        <section className="pt-6 border-t border-gray-200 text-base italic">
          <p>
            <strong>Data Collection:</strong> All responses are fully anonymous and handled in compliance 
            with Regulation (EU) 2016/679 (GDPR). No personally identifiable information is stored.
          </p>
          <p className="mt-2">
            <strong>Intellectual Property:</strong> All anime-related materials are property of their 
            respective owners and are used here solely for illustrative/academic purposes (Directive 2001/29/EC).
          </p>
        </section>
      </div>

      <div className="mt-12 text-center text-sm text-gray-500 italic">
        Doctoral Research Project | University of Bucharest |
       Coordinator: Professor Elena Stănculescu
      </div>
    </div>
  );
}

